runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
  static_files: dist/resume/\1
  upload: dist/resume/(.*)(|\.map)

- url: /.*
  static_files: dist/resume/index.html
  upload: dist/resume/index.html

- url: /.*
  static_files: dist/resume/index.html
  upload: dist/resume/(.*)
